- name: Install acl package
  ansible.builtin.package:
    name: acl
    state: present

- name: Ensure group app exists
  ansible.builtin.group:
    name: app
    state: present

- name: Ensure user ubuntu is in group app
  ansible.builtin.user:
    name: ubuntu
    groups: app
    append: yes

- name: Ensure /opt/opencrvs directory exists
  ansible.builtin.file:
    path: /opt/opencrvs
    state: directory
    mode: '0775'
    group: app

- name: Set permissions for /opt/opencrvs
  ansible.builtin.acl:
    path: /opt/opencrvs
    entity: app
    etype: group
    permissions: rw
    state: present
    recurse: yes

- name: Set ACL for a setup-deploy-config.log
  ansible.builtin.acl:
    path: /var/log/setup-deploy-config.log
    entity: app
    etype: group
    permissions: rw
    state: present

- name: Set ACL for a rotate-secrets.log
  ansible.builtin.acl:
    path: /var/log/rotate-secrets.log
    entity: app
    etype: group
    permissions: rw
    state: present
